version: "3.8"

services:
  backend: 
    image: 738175983873/vidly_backend
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    restart: unless-stopped    

volumes:
  vidly:
